[package]
name = "helix-sst-zen"
version = "0.1.6"
edition = "2024"
description = "Helix-SST standalone distraction-free editor"

[dependencies]
anyhow = "1.0"
arboard = "3.6.1"
crossterm = "0.29"
fontdue = "0.9.4"
portable-pty = "0.9.0"
raw-window-handle = "0.6.2"
serde_json = "1.0"
slint = { version = "1.18.1", default-features = false, features = ["std", "backend-winit", "renderer-femtovg", "compat-1-18", "raw-window-handle-06", "unstable-winit-030"] }
spellbook = "0.4.2"
toml = "0.5"
vt100 = "0.16"
zip = "0.6"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging"
] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
